name: "Issue 报告"
description: 反馈 Bug / 使用问题 / 建议（请尽量附 BookID 与日志）
title: "[Issue] "
labels: ["NEW"]
body:
  - type: markdown
    attributes:
      value: |
        感谢反馈！为了更快定位问题，请尽量提供：
        - **BookID**（若与书籍相关）
        - **日志压缩包**（程序根目录 `logs/` 下最近一次日志目录打包 zip）

        > 日志示例路径：`./logs/log_YYYYMMDD_HHMMSS/`
        > 可将该目录压缩为 zip 后，直接拖拽到 Issue 文本框上传。

  - type: dropdown
    id: issue_type
    attributes:
      label: 问题类型
      description: 请选择最接近的类型
      options:
        - Bug（功能异常/报错）
        - Question（使用疑问）
        - Enhancement（功能建议）
        - Documentation（文档问题）
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 问题描述
      description: 发生了什么？你期望的结果是什么？
      placeholder: |
        例如：下载到第 120 章报错退出，期望自动重试并继续下载。
    validations:
      required: true

  - type: input
    id: book_id
    attributes:
      label: BookID（可选但建议）
      description: 若问题与某本书相关，请填写 BookID 或书籍链接
      placeholder: 例如：7457335448529013785 或 https://...
    validations:
      required: false

  - type: textarea
    id: reproduce_steps
    attributes:
      label: 复现步骤（可选但建议）
      description: 尽量按步骤描述，方便快速复现
      placeholder: |
        1. 执行了什么命令/操作
        2. 输入了哪些参数
        3. 发生了什么错误
    validations:
      required: false

  - type: input
    id: env_info
    attributes:
      label: 环境信息（可选）
      description: 操作系统、程序版本、运行方式（CLI/WebUI）等
      placeholder: 例如：Windows 11 / v1.2.3 / CLI
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: 日志与附件（建议）
      description: |
        请上传程序根目录 `logs/` 下最近一次日志目录的压缩包（zip）。
        也可粘贴关键报错片段。
      placeholder: |
        - 已附 zip：是/否
        - 关键报错：
        - 其他补充：
    validations:
      required: false
